const products = [
  {
    id: 1,
    name: "Premium King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain2.png",
    alt: "Premium King Rox Keychain",
    coins: "1K Coin",
    featured: true,
  },
  {
    id: 2,
    name: "Classic King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain1.png",
    alt: "Classic King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 3,
    name: "Premium King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain2.png",
    alt: "Premium King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 4,
    name: "Classic King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain1.png",
    alt: "Classic King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 5,
    name: "Premium King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain2.png",
    alt: "Premium King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 6,
    name: "Classic King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain1.png",
    alt: "Classic King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 7,
    name: "Premium King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain2.png",
    alt: "Premium King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 8,
    name: "Classic King Rox Keychain",
    price: "$3.00",
    image: "./imgs/keychain1.png",
    alt: "Classic King Rox Keychain",
    coins: "1K Coin",
    featured: false,
  },
  {
    id: 9,
    name: "Crimson Velocity Pendant",
    price: "$3.00",
    image: "./imgs/keychain1.png",
    alt: "Crimson Velocity Pendant",
    coins: "150 Coin",
    featured: false,
  },
  {
    id: 10,
    name: "Emerald Guardian Keyring",
    price: "$3.00",
    image: "./imgs/keychain2.png",
    alt: "Emerald Guardian Keyring",
    coins: "150 Coin",
    featured: false,
  },
  {
    id: 11,
    name: "Lunar Eclipse Charm",
    price: "$3.00",
    image: "./imgs/keychain1.png",
    alt: "Lunar Eclipse Charm",
    coins: "150 Coin",
    featured: false,
  },
  {
    id: 12,
    name: "Infinity Loop Keychain",
    price: "$3.00",
    image: "./imgs/keychain2.png",
    alt: "Infinity Loop Keychain",
    coins: "150 Coin",
    featured: false,
  },
];
